version: "3.9"
services:
  portainer:
    name: portainer
    image: portainer/portainer
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/data/portainer:/data
    ports:
      - "9000:9000"