{
 "title": "Raspberry Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"node-exporter:9100\", job=\"node\"}"
    }
   ]
  },
  {
   "title": "Used SD",
   "type": "gauge",
   "description": "Show how much memory is been used by the system",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"/dev/root\", fstype=\"ext4\", instance=\"node-exporter:9100\", job=\"node\", mountpoint=\"/etc/hosts\"} / 1024 / 1024 / 1024) - (node_filesystem_free_bytes{device=\"/dev/root\", fstype=\"ext4\", instance=\"node-exporter:9100\", job=\"node\", mountpoint=\"/etc/hosts\"} / 1024 / 1024 / 1024)"
    }
   ]
  },
  {
   "title": "Available SD",
   "type": "gauge",
   "description": "Show how much memory is available for use.",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{device=\"/dev/root\", fstype=\"ext4\", instance=\"node-exporter:9100\", job=\"node\", mountpoint=\"/etc/hosts\"} / 1024 / 1024 / 1024)"
    }
   ]
  },
  {
   "title": "Hardware Temperature",
   "type": "gauge",
   "description": "Show the temperature from Raspberry Pi",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\", instance=\"node-exporter:9100\", job=\"node\", sensor=\"temp0\"}"
    }
   ]
  },
  {
   "title": "Alert List",
   "type": "alertlist",
   "gridPos": { "h": 23, "w": 4, "x": 20, "y": 0 },
   "targets": [
    { "expr": "node_uname_info" }
   ]
  }
 ]
}