{
 "title": "Raspberry Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"node-exporter:9100\", job=\"node\"}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "description": "Show how much of the disk is been used.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"node.*\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"node.*\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"node.*\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Show how much memory is been used by the system.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"node-exporter:9100\", job=\"node\"} - node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\", job=\"node\"}) / node_memory_MemTotal_bytes{instance=\"node-exporter:9100\", job=\"node\"}) * 100"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "gauge",
   "description": "Show how much swap is been used by the system.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"node-exporter:9100\", job=\"node\"} - node_memory_SwapFree_bytes{instance=\"node-exporter:9100\", job=\"node\"})"
    }
   ]
  },
  {
   "title": "Hardware Temperature",
   "type": "gauge",
   "description": "Show the temperature from Raspberry Pi",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\", instance=\"node-exporter:9100\", job=\"node\", sensor=\"temp0\"}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "The average network traffic received.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1m]))",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total[1m]))",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Show the CPU usage percentage graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[1m])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "timeseries",
   "description": "Show how much space of disk is using.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/root\", fstype=\"ext4\", instance=\"node-exporter:9100\", job=\"node\", mountpoint=\"/etc/hosts\"} - node_filesystem_free_bytes{device=\"/dev/root\", fstype=\"ext4\", instance=\"node-exporter:9100\", job=\"node\", mountpoint=\"/etc/hosts\"}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "description": "How much memory is available for use.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes\n", "legendFormat": "host" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Show the temperature from Raspberry Pi in a period",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"thermal_thermal_zone0\", instance=\"node-exporter:9100\", job=\"node\", sensor=\"temp0\"}"
    }
   ]
  },
  {
   "title": "Used SD",
   "type": "gauge",
   "description": "Show how much memory is been used by the system",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"/dev/root\", fstype=\"ext4\", instance=\"node-exporter:9100\", job=\"node\", mountpoint=\"/etc/hosts\"} / 1024 / 1024 / 1024) - (node_filesystem_free_bytes{device=\"/dev/root\", fstype=\"ext4\", instance=\"node-exporter:9100\", job=\"node\", mountpoint=\"/etc/hosts\"} / 1024 / 1024 / 1024)"
    }
   ]
  },
  {
   "title": "Available SD",
   "type": "gauge",
   "description": "Show how much memory is available for use.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{device=\"/dev/root\", fstype=\"ext4\", instance=\"node-exporter:9100\", job=\"node\", mountpoint=\"/etc/hosts\"} / 1024 / 1024 / 1024)"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Show the I/O from disk",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-sum(rate(node_disk_read_bytes_total[1m])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[1m])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  }
 ]
}